spring:
  datasource:
    url: ${C_DB_URL}
    username: ${C_DB_USER}
    password: ${C_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  swagger-ui:
    path: /openapi

app:
  security:
    jwt:
      issuer: ${C_JWT_ISSUER}
      algorithm: ${C_JWT_ALGORITHM}
      ttl: ${C_JWT_TTL}
      publicKey: ${C_JWT_PUBLIC_KEY}
      privateKey: ${C_JWT_PRIVATE_KEY}
