version: '3.1'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: devuser
      POSTGRES_DB: cirkle
    ports:
      - "6432:5432"